#!/usr/bin/env node
/**
 * Copies the Fluent 3D emoji (Microsoft, MIT — via @lobehub/fluent-emoji-3d)
 * for every emoji used in src/ into public/emoji/, and writes the lookup table
 * the <Emoji> component uses. Re-run after adding emoji to content or UI:
 *
 *   npm run emoji
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const assets = join(root, "node_modules/@lobehub/fluent-emoji-3d/assets");
const out = join(root, "public/emoji");
const table = join(root, "src/lib/emoji-assets.ts");

if (!existsSync(assets)) {
  console.error("Missing @lobehub/fluent-emoji-3d — run npm install first.");
  process.exit(1);
}

function walk(dir) {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) return walk(p);
    return /\.(ts|tsx)$/.test(f) && p !== table ? [p] : [];
  });
}

// Pictographic emoji, optionally with VS16, skin tone, keycap and ZWJ joins.
const EMOJI = /\p{Extended_Pictographic}️?(?:\p{Emoji_Modifier})?(?:‍\p{Extended_Pictographic}️?(?:\p{Emoji_Modifier})?)*/gu;

/** Lookup key: lowercase hex code points joined by "-", without VS16. */
export function emojiKey(e) {
  return [...e]
    .filter((c) => c !== "️")
    .map((c) => c.codePointAt(0).toString(16))
    .join("-");
}

const available = new Map(); // key without fe0f → file stem
for (const f of readdirSync(assets)) {
  const stem = f.replace(/\.webp$/, "");
  available.set(stem.split("-").filter((p) => p !== "fe0f").join("-"), stem);
}

// The package's file names swap two skin tones: its "1f3fc" art is medium
// and its "1f3fd" art is medium-light. Swap them back so the tone a child
// picks is the tone they see.
const TONE_FIX = { "1f3fc": "1f3fd", "1f3fd": "1f3fc" };
const sourceKey = (key) => key.split("-").map((p) => TONE_FIX[p] ?? p).join("-");

const used = new Set();
for (const file of walk(join(root, "src"))) {
  for (const m of readFileSync(file, "utf8").matchAll(EMOJI)) used.add(m[0]);
}

mkdirSync(out, { recursive: true });
const files = {};
const missing = [];
for (const e of [...used].sort()) {
  const key = emojiKey(e);
  const stem = available.get(sourceKey(key));
  if (!stem) {
    missing.push(e);
    continue;
  }
  copyFileSync(join(assets, `${stem}.webp`), join(out, `${key}.webp`));
  files[key] = true;
}

const keys = Object.keys(files).sort();
// Drop art no longer used anywhere.
for (const f of readdirSync(out)) {
  if (f.endsWith(".webp") && !files[f.replace(/\.webp$/, "")]) unlinkSync(join(out, f));
}
writeFileSync(
  table,
  `// Generated by scripts/sync-emoji.mjs — do not edit by hand.\n` +
    `// Fluent Emoji 3D © Microsoft, MIT licence.\n` +
    `export const EMOJI_ASSETS: ReadonlySet<string> = new Set(${JSON.stringify(keys, null, 2)});\n`,
);
// List for the service worker to pre-cache, so the art works offline.
// Our own art (public/art, see CUSTOM_ART in src/lib/emoji.ts) is cached too.
const art = existsSync(join(root, "public/art")) ? readdirSync(join(root, "public/art")).map((f) => `/art/${f}`) : [];
writeFileSync(join(out, "manifest.json"), JSON.stringify([...keys.map((k) => `/emoji/${k}.webp`), ...art]) + "\n");
console.log(`Synced ${keys.length} emoji to ${relative(root, out)}/`);
if (missing.length) console.log(`No Fluent 3D art (shown as text): ${missing.join(" ")}`);
